{% set name = "homonim" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/homonim-{{ version }}.tar.gz
  sha256: 4fb177fa1cbc5ac79fe0981c567e50aa259a3b9a1b7a7438ec6e871b6b64ec2b

build:
  entry_points:
    - homonim=homonim.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - click >=8
    - numpy >=1.19
    - opencv >=4.5
    - pandas >=1.1
    - python >=3.6
    - pyyaml >=5.4
    - rasterio >=1.1
    - tqdm >=4.6

test:
  imports:
    - homonim
  commands:
    - homonim --help
  requires:
    - pip

about:
  home: https://github.com/dugalh/homonim
  summary: |
    Radiometric homogenisation of aerial and satellite imagery by fusion with
    satellite surface reflectance data.
  license: AGPL-3.0-only
  license_file: LICENSE
  description: |
    `homonim` corrects multi-spectral aerial and satellite imagery to
    approximate surface reflectance, by fusion with concurrent and collocated
    satellite surface reflectance data.  It is a form of *spectral
    harmonisation*, that  adjusts for spatially varying atmospheric and
    anisotropic (BRDF) effects, without the need for manual reflectance
    measurements, or target placements.
    It is useful as a pre-processing step for quantitative mapping
    applications, such as biomass estimation or precision agriculture,
    and can be applied to drone, aerial or satellite imagery.

extra:
  recipe-maintainers:
    - dugalh
